name: camera_example
description: Demonstrates how to use the camera plugin.
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  camera: ^0.9.7
  flutter:
    sdk: flutter
  path_provider: ^2.0.0
  video_player: ^2.1.4
  video_player_elinux:
    git:
      url: https://github.com/matsch82/flutter-elinux-plugins.git
      path: packages/video_player
      ref: mschaff/main

dev_dependencies:
  build_runner: ^2.1.10
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
